/*
 * sherpa_msg microblx function block (autogenerated, don't edit)
 */

#include <ubx.h>

/* includes types and type metadata */

ubx_type_t types[] = {
        { NULL },
};

/* block meta information */
char sherpa_msg_meta[] =
        " { doc='ZMQ REQ-REP server',"
        "   real-time=false,"
        "}";

/* declaration of block configuration */
ubx_config_t sherpa_msg_config[] = {
        { .name="bridge_direction", .type_name = "int", .doc="Variable to determine if this bridge encodes (sends) or decodes (receives) messages. 1 = SEND, 2 = RECEIVE." },
        { NULL },
};

/* declaration port block ports */
ubx_port_t sherpa_msg_ports[] = {
        { .name="msg_in", .out_type_name="unsigned char", .doc="JSON byte stream to be processed"  },
        { .name="msg_out", .in_type_name="unsigned char", .doc="Resulting JSON byte stream."  },
        { NULL },
};

/* declare a struct port_cache */
struct sherpa_msg_port_cache {
        ubx_port_t* msg_in;
        ubx_port_t* msg_out;
};

/* declare a helper function to update the port cache this is necessary
 * because the port ptrs can change if ports are dynamically added or
 * removed. This function should hence be called after all
 * initialization is done, i.e. typically in 'start'
 */
static void update_port_cache(ubx_block_t *b, struct sherpa_msg_port_cache *pc)
{
        pc->msg_in =  ubx_port_get(b, "msg_in");
        pc->msg_out = ubx_port_get(b, "msg_out");
}


/* for each port type, declare convenience functions to read/write from ports */
//def_read_fun(read_zmq_req, unsigned char)

/* block operation forward declarations */
int sherpa_msg_init(ubx_block_t *b);
int sherpa_msg_start(ubx_block_t *b);
void sherpa_msg_stop(ubx_block_t *b);
void sherpa_msg_cleanup(ubx_block_t *b);
void sherpa_msg_step(ubx_block_t *b);


/* put everything together */
ubx_block_t sherpa_msg_block = {
        .name = "sherpa_msg",
        .type = BLOCK_TYPE_COMPUTATION,
        .meta_data = sherpa_msg_meta,
        .configs = sherpa_msg_config,
        .ports = sherpa_msg_ports,

        /* ops */
        .init = sherpa_msg_init,
        .start = sherpa_msg_start,
        .stop = sherpa_msg_stop,
        .cleanup = sherpa_msg_cleanup,
        .step = sherpa_msg_step,
};


/* sherpa_msg module init and cleanup functions */
int sherpa_msg_mod_init(ubx_node_info_t* ni)
{
        DBG(" ");
        int ret = -1;
        ubx_type_t *tptr;

        for(tptr=types; tptr->name!=NULL; tptr++) {
                if(ubx_type_register(ni, tptr) != 0) {
                        goto out;
                }
        }

        if(ubx_block_register(ni, &sherpa_msg_block) != 0)
                goto out;

        ret=0;
out:
        return ret;
}

void sherpa_msg_mod_cleanup(ubx_node_info_t *ni)
{
        DBG(" ");
        const ubx_type_t *tptr;

        for(tptr=types; tptr->name!=NULL; tptr++)
                ubx_type_unregister(ni, tptr->name);

        ubx_block_unregister(ni, "sherpa_msg");
}

/* declare module init and cleanup functions, so that the ubx core can
 * find these when the module is loaded/unloaded */
UBX_MODULE_INIT(sherpa_msg_mod_init)
UBX_MODULE_CLEANUP(sherpa_msg_mod_cleanup)
