/* Standalone C-only system (no scripting layer).
 *   This source has been autogenerated
 *     from a usc system description.
 */

#include <ubx.h>

#define WEBIF_PORT      "8888"
int main(int argc, char **argv)
{
  int len, ret=EXIT_FAILURE;
  ubx_node_info_t ni;
//   char* tmp_char;
  /* initalize the node */
  ubx_node_init(&ni, "cpp_transfer_app");
  ubx_block_t *webif;
    ubx_data_t *d;
  ubx_block_t *cpp_receiver1_4;
  ubx_block_t *ptrig1_1;
  ubx_block_t *cpp_sender1_3;
  ubx_block_t *fifo1_2;

  /* Load Modules */
  if(ubx_module_load(&ni, "/home/haianos/enea_microblx/microblx/std_types/stdtypes/stdtypes.so") != 0)
    goto out;
  
  if(ubx_module_load(&ni, "/home/haianos/enea_microblx/microblx/std_blocks/ptrig/ptrig.so") != 0)
    goto out;
  
  if(ubx_module_load(&ni, "/home/haianos/enea_microblx/microblx/std_blocks/lfds_buffers/lfds_cyclic.so") != 0)
    goto out;
  
  if(ubx_module_load(&ni, "/home/haianos/enea_microblx/microblx/std_blocks/hexdump/hexdump.so") != 0)
    goto out;
  
  if(ubx_module_load(&ni, "/home/haianos/enea_microblx/install/lib/microblx/blocks/cpp_sender.so") != 0)
    goto out;
  
  if(ubx_module_load(&ni, "/home/haianos/enea_microblx/install/lib/microblx/blocks/cpp_receiver.so") != 0)
    goto out;
  

  /* load the web-interface block */
  if(ubx_module_load(&ni, "/home/haianos/enea_microblx/microblx/std_blocks/webif/webif.so") != 0)
    goto out;
    
  printf("All modules have been loaded!\n");
  
  /* Create blocks */
  /* create ptrig1 block, instance of std_triggers/ptrig */
  if((ptrig1_1 = ubx_block_create(&ni, "std_triggers/ptrig", "ptrig1_1"))==NULL)
    goto out;
    
  /* create fifo1 block, instance of lfds_buffers/cyclic */
  if((fifo1_2 = ubx_block_create(&ni, "lfds_buffers/cyclic", "fifo1_2"))==NULL)
    goto out;
    
  /* create cpp_sender1 block, instance of cpp_sender */
  if((cpp_sender1_3 = ubx_block_create(&ni, "cpp_sender", "cpp_sender1_3"))==NULL)
    goto out;
    
  /* create cpp_receiver1 block, instance of cpp_receiver */
  if((cpp_receiver1_4 = ubx_block_create(&ni, "cpp_receiver", "cpp_receiver1_4"))==NULL)
    goto out;
    
  /* create a webserver block */
  if((webif = ubx_block_create(&ni, "webif/webif", "webif1"))==NULL)
    goto out;
  
  printf("All modules have been created!\n");
  
  /* Configure blocks */
  /* configuration of fifo1_2  */
  d = ubx_config_get_data(fifo1_2,"buffer_len");
  ubx_data_resize(d,data_size(d));
  *(uint32_t*)(d->data) = (uint32_t)(1);
  d = ubx_config_get_data(fifo1_2,"type_name");
  ubx_data_resize(d,strlen("struct cpp_data")+1);
  strncpy(d->data,"struct cpp_data",strlen("struct cpp_data")+1);
  /* configuration of ptrig1_1  */

  /* Configure port of webserver block
  * this gets the ubx_data_t pointer */
  d = ubx_config_get_data(webif, "port");
  len = strlen(WEBIF_PORT)+1;
    
  /* resize the char array as necessary and copy the port string */
  ubx_data_resize(d, len);
  strncpy(d->data, WEBIF_PORT, len);
  
  /* Connect blocks            */
  ubx_port_connect_out(ubx_port_get(cpp_sender1_3,"output" ), fifo1_2 );
  ubx_port_connect_in(ubx_port_get(cpp_receiver1_4,"input" ), fifo1_2 ); 
  
  /* INIT and START the BLOCKS */
  if(ubx_block_init(cpp_receiver1_4) != 0) {
    ERR("failed to init cpp_receiver1_4");
    goto out;
  }
  if(ubx_block_init(ptrig1_1) != 0) {
    ERR("failed to init ptrig1_1");
    goto out;
  }
  if(ubx_block_init(cpp_sender1_3) != 0) {
    ERR("failed to init cpp_sender1_3");
    goto out;
  }
  if(ubx_block_init(fifo1_2) != 0) {
    ERR("failed to init fifo1_2");
    goto out;
  }
  printf("All blocks have been initialized!\n");

  if(ubx_block_start(cpp_receiver1_4) != 0) {
    ERR("failed to start cpp_receiver1_4");
    goto out;
  }
  if(ubx_block_start(ptrig1_1) != 0) {
    ERR("failed to start ptrig1_1");
    goto out;
  }
  if(ubx_block_start(cpp_sender1_3) != 0) {
    ERR("failed to start cpp_sender1_3");
    goto out;
  }
  if(ubx_block_start(fifo1_2) != 0) {
    ERR("failed to start fifo1_2");
    goto out;
  }
  printf("All blocks have been started!\n");
  
  /*        web interface       */
  if(ubx_block_init(webif) != 0) {
    ERR("failed to init webif");
    goto out;
  }

  if(ubx_block_start(webif) != 0) {
    ERR("failed to start webif");
    goto out;
  }
  printf("webif block lauched on port %s\n", WEBIF_PORT);
    
  printf("Everything is up and running! hit enter to quit\n");
  getchar();

  ret=EXIT_SUCCESS;
out:
  /* this cleans up all blocks and unloads all modules */
  ubx_node_cleanup(&ni);
  exit(ret);  
}

