/*
 * cpp_receiver microblx function block (autogenerated, don't edit)
 */

#include <ubx.h>

/* includes types and type metadata */
#include "../types/cpp_data.h"
#include "../types/cpp_data.h.hexarr"

ubx_type_t types[] = {};

/* block meta information */
char cpp_receiver_meta[] =
        " { doc='',"
        "   real-time=true,"
        "}";

/* declaration of block configuration */
ubx_config_t cpp_receiver_config[] = {
        { NULL },
};

/* declaration port block ports */
ubx_port_t cpp_receiver_ports[] = {
        { .name="input", .in_type_name="struct cpp_data", .in_data_len=1, .doc="input port for cpp data"  },
        { NULL },
};

/* declare a struct port_cache */
struct cpp_receiver_port_cache {
        ubx_port_t* input;
};

/* declare a helper function to update the port cache this is necessary
 * because the port ptrs can change if ports are dynamically added or
 * removed. This function should hence be called after all
 * initialization is done, i.e. typically in 'start'
 */
static void update_port_cache(ubx_block_t *b, struct cpp_receiver_port_cache *pc)
{
        pc->input = ubx_port_get(b, "input");
}


/* for each port type, declare convenience functions to read/write from ports */
def_read_fun(read_input, struct cpp_data)

/* block operation forward declarations */
int cpp_receiver_init(ubx_block_t *b);
int cpp_receiver_start(ubx_block_t *b);
void cpp_receiver_stop(ubx_block_t *b);
void cpp_receiver_cleanup(ubx_block_t *b);
void cpp_receiver_step(ubx_block_t *b);


/* put everything together */
ubx_block_t cpp_receiver_block = {
        .name = "cpp_receiver",
        .type = BLOCK_TYPE_COMPUTATION,
        .meta_data = cpp_receiver_meta,
        .configs = cpp_receiver_config,
        .ports = cpp_receiver_ports,

        /* ops */
        .init = cpp_receiver_init,
        .start = cpp_receiver_start,
        .stop = cpp_receiver_stop,
        .cleanup = cpp_receiver_cleanup,
        .step = cpp_receiver_step,
};


/* cpp_receiver module init and cleanup functions */
int cpp_receiver_mod_init(ubx_node_info_t* ni)
{
        DBG(" ");
        int ret = -1;
        ubx_type_t *tptr;

        for(tptr=types; tptr->name!=NULL; tptr++) {
                if(ubx_type_register(ni, tptr) != 0) {
                        goto out;
                }
        }

        if(ubx_block_register(ni, &cpp_receiver_block) != 0)
                goto out;

        ret=0;
out:
        return ret;
}

void cpp_receiver_mod_cleanup(ubx_node_info_t *ni)
{
        DBG(" ");
        const ubx_type_t *tptr;

        for(tptr=types; tptr->name!=NULL; tptr++)
                ubx_type_unregister(ni, tptr->name);

        ubx_block_unregister(ni, "cpp_receiver");
}

/* declare module init and cleanup functions, so that the ubx core can
 * find these when the module is loaded/unloaded */
UBX_MODULE_INIT(cpp_receiver_mod_init)
UBX_MODULE_CLEANUP(cpp_receiver_mod_cleanup)
