/*
 * module function declaration for library czmqppworkerlib header (autogenerated)
 */

#include "czmqppworkerlib_module.h"

int czmqppworkerlib_mod_init(ubx_node_info_t* ni)
{
  int ret;
  ret=czmq_ppworker_mod_init(ni);
  if(ret!=0)
    goto out;

out:
   return ret;
}

void czmqppworkerlib_mod_cleanup(ubx_node_info_t* ni)
{
  czmq_ppworker_mod_cleanup(ni);
}

